# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Todo
  pod 'AppCenter/Crashes', '~> 1.1.0'
  pod 'AppCenter/Analytics', '~> 1.1.0'
  pod 'AppCenterReactNativeShared', '~> 1.1.0'

  

  target 'TodoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Todo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Todo-tvOS

  target 'Todo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
